CREATE TABLE IF NOT EXISTS "user" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    mobile VARCHAR(15),
    password_hash VARCHAR(256) NOT NULL,
    avatar VARCHAR(200) NOT NULL DEFAULT '',
    theme VARCHAR(20) NOT NULL DEFAULT 'system' CHECK (theme IN ('light', 'dark', 'system')),
    primary_currency VARCHAR(10) NOT NULL DEFAULT 'INR' CHECK (primary_currency IN ('INR', 'USD', 'EUR', 'GBP', 'AED', 'SAR', 'SGD', 'JPY', 'AUD', 'CAD')),
    two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    two_factor_secret VARCHAR(64),
    failed_login_count INTEGER NOT NULL DEFAULT 0 CHECK (failed_login_count >= 0),
    locked_until TIMESTAMP,
    last_login_at TIMESTAMP,
    last_login_ip VARCHAR(50),
    password_changed_at TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS category (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES "user"(id),
    name VARCHAR(100) NOT NULL,
    subcategory VARCHAR(100) NOT NULL,
    category_type VARCHAR(30) NOT NULL CHECK (category_type IN ('Income', 'Expense', 'Not Reported')),
    is_system BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CHECK ((is_system AND user_id IS NULL) OR (NOT is_system AND user_id IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS account (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES "user"(id),
    name VARCHAR(100) NOT NULL,
    account_type VARCHAR(50) NOT NULL CHECK (account_type IN ('bank', 'investment', 'wallet', 'other')),
    sub_type VARCHAR(50),
    institution VARCHAR(100),
    account_number VARCHAR(50),
    currency VARCHAR(10) NOT NULL DEFAULT 'INR' CHECK (currency IN ('INR', 'USD', 'EUR', 'GBP', 'AED', 'SAR', 'SGD', 'JPY', 'AUD', 'CAD')),
    opening_balance NUMERIC(14, 2) NOT NULL DEFAULT 0,
    current_balance NUMERIC(14, 2) NOT NULL DEFAULT 0,
    color VARCHAR(20) NOT NULL DEFAULT '#6366f1',
    icon VARCHAR(10) NOT NULL DEFAULT '🏦',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes TEXT,
    start_date DATE,
    maturity_date DATE,
    due_date DATE,
    notification_days INTEGER CHECK (notification_days BETWEEN 1 AND 30),
    installment_date DATE,
    installment_amount NUMERIC(14, 2) CHECK (installment_amount >= 0),
    installment_type VARCHAR(10),
    denom_data TEXT,
    machine_name VARCHAR(100),
    CHECK (opening_balance >= 0)
);

CREATE TABLE IF NOT EXISTS denomination (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER NOT NULL REFERENCES account(id),
    denomination_value INTEGER NOT NULL CHECK (denomination_value IN (1, 2, 5, 10, 20, 50, 100, 200, 500, 2000)),
    count INTEGER NOT NULL DEFAULT 0 CHECK (count >= 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (account_id, denomination_value)
);

CREATE TABLE IF NOT EXISTS "transaction" (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES "user"(id),
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    amount NUMERIC(14, 2) NOT NULL CHECK (amount > 0),
    txn_type VARCHAR(20) NOT NULL CHECK (txn_type IN ('Income', 'Expense', 'Not Reported')),
    category_id INTEGER REFERENCES category(id),
    payment_mode VARCHAR(30) CHECK (payment_mode IS NULL OR payment_mode IN ('Cash', 'UPI', 'NEFT', 'RTGS', 'IMPS', 'NACH', 'Credit Card', 'Debit Card', 'Net Banking', 'Cheque', 'EMI', 'Auto Debit', 'Wallet')),
    account_id INTEGER REFERENCES account(id),
    transfer_account_id INTEGER REFERENCES account(id),
    linked_transaction_id INTEGER REFERENCES "transaction"(id),
    description VARCHAR(255),
    reference_no VARCHAR(100),
    tags VARCHAR(200),
    denom_data TEXT,
    machine_name VARCHAR(100),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (transfer_account_id IS NULL OR account_id IS NULL OR transfer_account_id <> account_id)
);

CREATE TABLE IF NOT EXISTS schedule (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES "user"(id),
    name VARCHAR(100) NOT NULL,
    amount NUMERIC(14, 2) NOT NULL CHECK (amount > 0),
    category_id INTEGER REFERENCES category(id),
    account_id INTEGER REFERENCES account(id),
    payment_mode VARCHAR(30) CHECK (payment_mode IS NULL OR payment_mode IN ('Cash', 'UPI', 'NEFT', 'RTGS', 'IMPS', 'NACH', 'Credit Card', 'Debit Card', 'Net Banking', 'Cheque', 'EMI', 'Auto Debit', 'Wallet')),
    frequency VARCHAR(20) NOT NULL CHECK (frequency IN ('monthly', 'quarterly', 'half-yearly', 'yearly', 'weekly')),
    due_day INTEGER NOT NULL CHECK (due_day BETWEEN 1 AND 31),
    next_due DATE,
    remind_days_before INTEGER NOT NULL DEFAULT 3 CHECK (remind_days_before BETWEEN 1 AND 30),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS notification (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES "user"(id),
    schedule_id INTEGER REFERENCES schedule(id),
    message VARCHAR(300),
    due_date DATE,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES "user"(id),
    table_name VARCHAR(50) NOT NULL,
    record_id INTEGER NOT NULL,
    action VARCHAR(20) NOT NULL CHECK (action IN ('INSERT', 'UPDATE', 'DELETE')),
    old_data TEXT,
    new_data TEXT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS password_reset (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES "user"(id),
    token VARCHAR(128) NOT NULL UNIQUE,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_user_email_casefold ON "user"(LOWER(email));
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_mobile ON "user"(mobile) WHERE mobile IS NOT NULL AND mobile <> '';
CREATE UNIQUE INDEX IF NOT EXISTS uq_system_category ON category(name, subcategory, category_type) WHERE user_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_category ON category(user_id, name, subcategory, category_type) WHERE user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_account_user_active ON account(user_id, is_active);
CREATE INDEX IF NOT EXISTS idx_category_user_active ON category(user_id, is_active);
CREATE INDEX IF NOT EXISTS idx_transaction_user_date ON "transaction"(user_id, date DESC, id DESC) WHERE is_deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_transaction_account_active ON "transaction"(account_id, is_deleted);
CREATE INDEX IF NOT EXISTS idx_transaction_category_active ON "transaction"(category_id, is_deleted);
CREATE INDEX IF NOT EXISTS idx_schedule_user_active_due ON schedule(user_id, is_active, next_due);
CREATE UNIQUE INDEX IF NOT EXISTS uq_notification_schedule_due ON notification(user_id, schedule_id, due_date);
CREATE INDEX IF NOT EXISTS idx_notification_user_read_due ON notification(user_id, is_read, due_date);
CREATE INDEX IF NOT EXISTS idx_audit_log_record ON audit_log(table_name, record_id, timestamp DESC);
